[package]
name = "evolve-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", features = ["api-4-4"] }
rand = "0.8"
rand_distr = "0.4"
